/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSarvamTtsRouteImport } from './routes/api/sarvam-tts'
import { Route as ApiPiyushAiRouteImport } from './routes/api/piyush-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSarvamTtsRoute = ApiSarvamTtsRouteImport.update({
  id: '/api/sarvam-tts',
  path: '/api/sarvam-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPiyushAiRoute = ApiPiyushAiRouteImport.update({
  id: '/api/piyush-ai',
  path: '/api/piyush-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/piyush-ai': typeof ApiPiyushAiRoute
  '/api/sarvam-tts': typeof ApiSarvamTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/piyush-ai': typeof ApiPiyushAiRoute
  '/api/sarvam-tts': typeof ApiSarvamTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/piyush-ai': typeof ApiPiyushAiRoute
  '/api/sarvam-tts': typeof ApiSarvamTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/piyush-ai' | '/api/sarvam-tts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/piyush-ai' | '/api/sarvam-tts'
  id: '__root__' | '/' | '/api/piyush-ai' | '/api/sarvam-tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPiyushAiRoute: typeof ApiPiyushAiRoute
  ApiSarvamTtsRoute: typeof ApiSarvamTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sarvam-tts': {
      id: '/api/sarvam-tts'
      path: '/api/sarvam-tts'
      fullPath: '/api/sarvam-tts'
      preLoaderRoute: typeof ApiSarvamTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/piyush-ai': {
      id: '/api/piyush-ai'
      path: '/api/piyush-ai'
      fullPath: '/api/piyush-ai'
      preLoaderRoute: typeof ApiPiyushAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPiyushAiRoute: ApiPiyushAiRoute,
  ApiSarvamTtsRoute: ApiSarvamTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
